### ISSUE TITLE
blockapss: distiguising functions calls and transfers

### ISSUE THREAD

**Issue by Firescar96** [blockapps/hserver-eth#30] opened 2015-07-22 23:03 UTC
When i send ether to an account using the blockapps api (specifically lightwalled) it appears on http://blockapps.net/demo/ as a function call instead of an ether transfer.

Of course the money ends up in the right place which is what matters, but still.

**Comment by jamshidh** [comment] 2015-10-24 17:09
I think this might be a duplicate of https://github.com/blockapps/hserver-eth/issues/14.

If I am correct, can you remark that here, and close this bug....

**Comment by kejace** [comment] 2015-10-28 04:53
I think demo is deprecated. Closing.

**Closed by kejace** 2015-10-28 04:53 UTC
